JoinMessage: 'Welcome to McStrike!'
AfkMessageOn: 'ยง5 You are afk now.'
AfkMessageOff: 'ยง4 You are no longer afk.'

classes: ["sniper", "assault", "infiltrator"]

Weaponss:
  - Guns:
      - M40A3:
          - Damage:
              - 20
          - Magazin:
              - 1
          - ReloadTime:
              - 3s
          - M21:
              - Damage:
                  - 8
              - Magazin:
                  - 0
              - ReloadTime:
                  - 0
          - AK47:
              - Damage:
                  - 6
              - Magazin:
                  - 30
              - ReloadTime:
                  - 5s
          - M16:
              - Damage:
                  - 5
              - Magazin:
                  - 30
              - ReloadTime:
                  - 3s
          - Famas:
              - Damage:
                  - 0
              - Magazin:
                  - 0
              - ReloadTime:
                  - 0
          - P90:
              - Damage:
                  - 0
              - Magazin:
                  - 0
              - ReloadTime:
                  - 0
          - M1014:
              - Damage:
                  - 0
              - Magazin:
                  - 8
              - ReloadTime:
                  - 0
          - Pistol:
              - Damage:
                  - 5
              - Magazin:
                  - 8
              - ReloadTime:
                  - 5s
  - Meele:
      - Knife:
          - Damage: 15
Classes:
  - Sniper:
      - Weapons:
          - Guns:
              - M40A3
              - Pistol
          - Meele:
              - Knife
      - Utilities:
          - Wardog
          - Claymore
  - Juggernaut:
      - Weapons:
          - Guns:
              - M1014
              - Pistol
          - Meele:
              - Knife
      - Utilities:
          - Barrier
          - Drone
  - Assault:
      - Weapons:
          - Guns:
              - AK47
              - Pistol
          - Meele:
              - Knife
      - Utilities:
          - Grenade
          - Flashbang
          - C4
  - Infiltrator:
      - Weapons:
          - Guns:
              - P90
              - Pistol
          - Meele:
              - Knife
      - Utilities:
          - SpeedJolt
